config/routes.rb
Rails.application.routes.draw do

  root "hacks#index"
  resources :hacks, shallow: true do
    resources :comments
  end

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :hack
  belongs_to :user
end

app/models/hack.rb
class Hack < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_attached_file :image, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


  def self.search(search)
    if search
      Hack.where("LOWER(name) LIKE ?", "%#{search}%".downcase)
    else
      Hack.all
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :hacks
  has_many :comments
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

    helper_method :current_user

    def current_user
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def authorize
      redirect_to login_path, alert: 'You must be logged in to do that.' if current_user.nil?
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = Comment.new(comment_params)
    @hack = Hack.find(params[:hack_id])
    @comment.user = current_user
    @comment.hack = @hack
    if @comment.save
      flash[:notice] = "Comment Created!"
      redirect_to @hack
    else
      render 'new'
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.user == current_user && @comment.update_attributes(comment_params)
      redirect_to @comment.hack
      flash[:notice] = "Comment Edited!"
    else
      render 'edit'
      flash.now[:notice] = 'Invalid User'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    hack = @comment.hack
    if @comment.user == current_user
      @comment.destroy
      flash[:notice] = "Comment Deleted!"
      redirect_to hack
    else
      flash[:notice] = "Invalid User"
      redirect_to hack
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/hacks_controller.rb
class HacksController < ApplicationController
  before_action :set_hack, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:index, :show]

  def index
    @hacks = Hack.search(params[:search])
    if params.key?(:sort)
      @desc = params[:desc] == 'true' ? 'false' : 'true'
      if params[:desc] == 'true'
        @hacks = @hacks.order("#{params[:sort]} DESC")
      else
        @hacks = @hacks.order("#{params[:sort]}")
      end
    else
      @hacks = @hacks.order("created_at DESC")
    end
  end

  def show
    @hack = Hack.find(params[:id])
    @comment = Comment.new
  end

  def new
    @hack = Hack.new
  end

  def edit
    if @hack.user == current_user
      @hack = Hack.find(params[:id])
    else
      redirect_to hacks_path
      flash[:notice] = "Invalid User"
    end
  end

  def create
    @hack = Hack.new(hack_params)
    @hack.user = current_user
    if @hack.save
      flash[:notice] = "Life Hack Created!"
      redirect_to hacks_path
    else
      render 'new'
    end
  end

  def update
    @hack = Hack.find(params[:id])
    if @hack.user == current_user && @hack.update_attributes(hack_params)
      redirect_to hacks_path
      flash[:notice] = "Life Hack Edited!"
    else
      render 'edit'
      flash.now[:notice] = 'Invalid User'
    end
  end

  def destroy
    @hack = Hack.find(params[:id])
    if @hack.user == current_user
      @hack.destroy
      flash[:notice] = "Life Hack Deleted!"
      redirect_to hacks_path
    else
      flash[:notice] = "Invalid User"
      redirect_to hacks_path
    end
  end

  private

  def set_hack
    @hack = Hack.find(params[:id])
  end

  def hack_params
    params.require(:hack).permit(:name, :image, :body)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid login credentials - try again!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully signed up!"
      redirect_to hacks_path
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment do |form| %>
  <%= form.label :body %>
  <%= form.text_area :body %><br>
  <%= form.submit 'Submit' %>
<% end %>

app/views/comments/edit.html.erb
<div class="jumbotron text-center">
  <h1>Edit Comment</h1>
  <%= render 'form' %>
</div>

app/views/comments/index.html.erb
<h1>Comments Index</h1>

app/views/comments/new.html.erb
<h1>Create new Comment</h1>

<%= render 'form' %>

app/views/comments/show.html.erb
<h1>See all comments</h1>

app/views/hacks/_form.html.erb
<div class="jumbotron text-center sign-up-form">
  <u><h1 class="text-center">Submit Life Hack</h1></u>
  <hr>
  <%= form_for @hack, html: { multipart: true } do |form| %>
    <h4><%= form.label :name %></h4>
    <%= form.text_field :name, :required => true %>
    <br>
    <h4><%= form.label "Description" %></h4>
    <%= form.text_area :body, :required => true %>
    <br>
    <%= form.file_field :image, id: "file-field" %>
    <br>
    <%= form.submit 'Submit', class: "btn btn-success" %>
    <%= link_to 'Go back', hacks_path, class: "btn btn-default" %>
  <% end %>
</div>

app/views/hacks/edit.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/hacks/index.html.erb
<a name="top"></a>
<p id="notice" class="text-center"><%= notice %></p>

<div class="container main-wrap-index panel-footer">
  <h2 class="text-center">All Life Hacks</h2>
  <ul class="nav nav-tabs">
    <!-- <li role="presentation" class="pull-left btn btn-success btn-xs"><%= link_to "New LifeHack", new_hack_path %></li> -->
    <%= form_tag hacks_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
      <div class="form-group main-search">
          <%= text_field_tag :search, params[:search], class: "form-control", placeholder: 'Enter search term...' %>
      </div>
      <%= submit_tag "Search", :name => nil, class: "btn btn-default main-search-submit" %>
    <% end %>
    <li role="presentation" class="pull-right desc-span"><%= link_to "View All", hacks_path(sort: 'created_at', desc: @desc) %></li></span>
    <li role="presentation" class="pull-right desc-span"><%= link_to "Date", hacks_path(sort: 'created_at', desc: @desc) %></li></span>
    <li role="presentation" class="pull-right desc-span"><%= link_to "Name", hacks_path(sort: 'name', desc: @desc) %></li></span>
    <!-- <li role="presentation" id="sub-nav" class="pull-right not-active"><a href="#">Sort By:</a></li> -->
  </ul>
    <div class="row text-center t-wrap">
    <% if @hacks.count == 0 %>
      <h3>No Hacks Match Your Search.</h3>
      <%= link_to "Go Back", hacks_path, class: "btn btn-default" %>
    <% else %>
      <% @hacks.each do |hack| %>
        <%= link_to hack_path(hack) do %>
          <div class="col-xs-12 col-sm-12 col-md-8 thumb-wrapper well well-sm">
            <h4 class="hack-name-wrap"><%= hack.name %></h4>
            <img src="<%= hack.image.url %>" class="img-responsive img-size thumbnail">
            <h5>@<%= hack.user.name %></h5>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="text-center">
    <a href="#top">Back to top</a>
  </div>
</div>

app/views/hacks/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/hacks/show.html.erb
<a name="top"></a>
<p id="notice"><%= notice %></p>
<div id="show-wrap-main" class="container main-wrap-show panel-footer">
  <div class="container text-center show-title">
    <h1 id="show-name" class="text-center"><%= @hack.name %></h1>
    <p class="text-center">by: <%= @hack.user.name %></p><br>
    <p id="show-go-back-btn" class="btn btn-info"><%= link_to 'Go Back', hacks_path %></p>
    <hr>
  </div>
    <div id="show-container" class="container text-center hack-info-page">
    <div class="row">
      <div class="col-lg-12 col-xs-12 col-sm-6 col-md-8">
        <% if @hack.user == current_user %>
          <%= link_to 'Edit', edit_hack_path %>
          <%= link_to 'Delete', hack_path(@hack), method: :delete, data: { confirm: "are you sure you want to delete this Lifehack?"} %>
        <% end %>
        <img src="<%= @hack.image.url %>" class="img-responsive show-img center-block">
      </div>
    </div>
    </div>
    <div id="hack-info-desc" class="col-lg-12 text-center">
      <h2>Description:</h2>
      <p><%= @hack.body %></p>
      <hr>
    </div>
  <div class="container">
    <% if current_user %>
    <div class="row">
      <div class="center-block">
        <%= form_for [@hack, @comment] do |form| %>
        <%= form.text_area :body, rows: '6', cols: '50', id: "comment-body", :required => true, class: "comment-input form-control", placeholder: 'Write a comment!' %><br>
        <%= form.submit 'Submit Comment', id: "comment-btn", class: "center-block btn btn-primary" %>
      </div>
    </div>
    <% end %>
        <% end %>

    <ul class="text-center comment-wrap">
    <h3 class="comments-h3">Comments:</h3>
      <% @hack.comments.each do |c| %>
        <li>
          <div class="comment-body panel panel-default">
            <div class="panel-heading">@<%= c.user.name %>&nbsp&nbsp|&nbsp&nbsp<%= c.created_at.localtime.strftime("%a %b %I:%M:%S %p") %></small></div>
            <div class="panel-body"><%= c.body %></div>
            <% if c.user == current_user %>
              <%= link_to "edit", edit_comment_path(c) %> | <%= link_to "delete", comment_path(c), method: :delete %>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
  <br>
  <div class="text-center">
    <a href="#top" class="btn btn-info">Back to top</a>
  </div>
  <br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LifeHacks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Noticia+Text" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <ul class="nav nav-tabs main-nav navbar-fixed-top">
    <% if current_user %>
      <li role="presentation" id="brand-name"><%= link_to 'Life Hacks', hacks_path %></li>
      <li role="presentation" class="pull-right"><%= link_to 'Log Out', session_path('dummy'), method: :delete %></li>
      <li role="presentation" class="pull-right" id="nav-new-hack-link"><%= link_to "New LifeHack", new_hack_path %></li>
      <!-- <li role="presentation" class="name-badge pull-right no-click"><a href="#"> Welcome, <%= current_user.name %> </a></li> -->
    <% else %>
      <li role="presentation" class=""><%= link_to 'Life Hacks', hacks_path %></li>
      <li role="presentation" class="pull-right"><%= link_to 'Log In', login_path %></li>
      <li role="presentation" class="pull-right"><%= link_to 'Sign Up', new_user_path %></li>
    <% end %>
  </ul>
  <%= yield %>


</body>
</html>

app/views/users/new.html.erb
<div class="container">
  <div class="jumbotron  sign-up-form">
    <h1 class="text-center">New Account</h1>
    <hr class="new-user-h">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Error:</h2>
            <% for message in @user.errors.full_messages %>
              <small><%= message %></small><br>
            <% end %>
        </div>
      <% end %>
      <div class="row">
        <div class="col-md-6">
          <form>
            <div class="form-group">
              <%= f.label "name:", class: "control-label new-form-bold" %><br>
              <%= f.text_field :name, :required => true, class: "controls", placeholder: "Name" %>
            </div>
            <div class="form-group">
              <%= f.label "email:", class: "control-label new-form-bold" %><br>
              <%= f.text_field :email, :required => true, class: "controls", placeholder: "Email" %>
            </div>
            <div class="form-group">
              <%= f.label "password:", class: "control-label new-form-bold" %><br>
              <%= f.password_field :password, :required => true, class: "controls", placeholder: "Password" %>
            </div>
            <div class="form-group">
              <%= f.label "Confirm Password:", class: "control-label new-form-bold" %><br>
              <%= f.password_field :password_confirmation, :required => true, class: "controls", placeholder: "Confirm Password" %>
            </div>
            <div class="actions"><%= f.submit 'Create Account', :class => "btn btn-success" %></div>
          <% end %>
        </form>
      </div>
      <div class="col-md-6">
        <u><h2><strong>Create Account to:</strong></h2></u>
        <p>-Upload new LifeHacks</p>
        <p>-Comment on LifeHacks</p>
      </div>
    </div>
  </div>
</div>